title: Yiqing (Selina) Xin - Personal Website
description: Hi, welcome to my website. I am Selina, a current M.Eng. student at Cornell, majoring in ORIE.  I hope to be a data analyst in the future.
url: "https://yx583.github.io"
